クラス　実装
kuwana0425/GeekationJavaBasic pull request #9
Opened 2024-07-17 06:58 UTC by kuwana0425

ご確認のほどよろしくお願いします🙇

2024-07-17 07:41 UTC, uchiyama4929 requested changes
![image](https://github.com/user-attachments/assets/27a59273-4ffe-4a6e-bcb5-8f146946ff03)
数値をコンソール出力するというデフォルト処理があるので追加してください。

2024-07-17 07:41 UTC, uchiyama4929 commented on src/basicSyntax/GeekIntroduction.java
> +		System.out.println("num1とnum2は0より大きい値にしてください。");
0と入力すると処理が動いてしまうようです。

2024-07-17 07:41 UTC, uchiyama4929 commented on src/basicSyntax/GeekIntroduction.java
> +		System.out.println("num2はnum1より大きい値にしてください。");
このエラー文が表示されないので確認してください。

2024-07-17 13:19 UTC, kuwana0425 commented
ご指摘ありがとうございます。
・デフォの数値コンソール出力
・”num2はnum1より大きい値にしてください。”のエラー文修正
・１つ目のif文を「num1 < 0 || num2 < 0 」へと変更

上記３点を修正しました。何卒よろしくお願いします🙇‍♀️

2024-07-18 02:00 UTC, uchiyama4929 requested changes

2024-07-18 02:00 UTC, uchiyama4929 commented on src/basicSyntax/GeekIntroduction.java
> +		System.out.println("num1とnum2は0より大きい値にしてください。");
この部分ですが一つ上の行にnum1++があるので入力された数字＋１からスタートしてしまっているのがそもそもの問題かと思います。

問題文にもnum1とnum2の数字を含むように出力することが定義されています。

要件では入力値が1より小さい場合 となっているので条件はこれで問題ないはずです。
今回はint型なので考慮する必要がないですが0.9とかの値が考えられる場合もあるのでこういった条件の改変は気をつける必要があります。

2024-07-18 02:00 UTC, uchiyama4929 commented on src/basicSyntax/GeekIntroduction.java
> +		System.out.println("num2はnum1より大きい値にしてください。");
> num1がnum2以上の場合

というのが問題文の要件なのでこの条件はこちらであっているのですが、実際にこの条件を満たす値を代入して動かしてエラー文を確認できているのでしょうか？

2024-07-22 02:31 UTC, uchiyama4929 commented
３や５などの数字をnum1にいれると最初のターンで倍数表示がされていないので修正をお願いします。

2024-07-22 02:32 UTC, uchiyama4929 commented
num1のほうが大きい場合のエラーメッセージは表示されていないようなので修正をお願いします。

2024-07-23 06:41 UTC, uchiyama4929 commented
> num1のほうが大きい場合のエラーメッセージは表示されていないようなので修正をお願いします。

こちらが治っていないようですね。
num1 = 51
num2 = 50

とかで動作してコンソール出力を確認してみてください。

2024-07-24 09:22 UTC, kuwana0425 commented
お疲れ様です🙇表示されました！ご確認よろしくお願いします。

2024-07-24 10:49 UTC, uchiyama4929 commented
![image](https://github.com/user-attachments/assets/67e6c53b-97d8-4820-84f1-713a36784545)

通常の動作時にカウントアップして最後必ずこの表示が出てしまうようですね。

このエラーメッセージはメソッド開始時に入力された値を検証するためのものなので修正をお願いします！

2024-07-24 11:37 UTC, kuwana0425 commented
ご指摘ありがとうございます💦先ほど修正いたしました🙇

2024-07-24 12:23 UTC, uchiyama4929 commented
いいですね。
こんな感じでいいのでもう一点修正しましょう。

例えば
num1 = 0
num2 = -1
だった場合に```num2はnum1より大きい値にしてください。```というメッセージが出ると思うのですが、
今回の要件であれば
* num1またはnum2が1より小さい場合
* num1がnum2以上の場合
* num1またはnum2が300より大きい場合

という優先順位でエラーメッセージが決まるべきだと思うので
```num1とnum2は0より大きい値にしてください。```というエラーが先に表示されて終了するようにしてみましょう。

2024-07-24 12:49 UTC, kuwana0425 commented
内山さん
コメントありがとうございます😢修正いたしました🙇

2024-07-25 05:09 UTC, uchiyama4929 commented
いい感じになったんですが、エラー文が出た後そのまま処理が続行してしまうのでnum1 = -1とかで入れた場合にエラー文の後にnum2までの番号が表示されてしまいますね。

2024-07-25 05:10 UTC, uchiyama4929 commented
あれ、いつからかわからないですが、1よりも小さくという条件が変わってしまっていますね。
こちらも修正をお願いします。

2024-07-25 15:11 UTC, kuwana0425 commented
ご指摘ありがとうございます🙇修正いたしました。

2024-07-29 05:56 UTC, kuwana0425 commented
何度も申し訳ございません。ご確認のほどよろしくお願いします。

2024-07-29 06:25 UTC, uchiyama4929 commented
なかなか要件通りの仕様にならないようですが、追加変更を行った後動作の確認は行っていますか？

以下にこちらの課題の動作要件を満たすための動作確認手順を記載しますので参考にしてみて動作確認を行ってください。

**1. 正常な範囲の入力**
入力: specialSkill(1, 300)
期待値:
```
1
2
3は3の倍数です。
4
5は5の倍数です。
6は3の倍数です。
7
8
9は3の倍数です。
10は5の倍数です。
...
300は3の倍数かつ5の倍数です。
```
※このケースにより 1未満NG と 300超NGという2つの要件の閾値ギリギリの値が許容されていることが確認できます。
このケースで全数でなくても3の倍数5の倍数 15の倍数の挙動を確認してください

**2. num1 または num2 が 1 より小さい場合**

入力: specialSkill(0, 1)
期待値: num1とnum2は0より大きい値にしてください。
入力: specialSkill(1, 0)
期待値: num1とnum2は0より大きい値にしてください。(num1 > num2エラーより優先)
入力: specialSkill(-1, 1)
期待値: num1とnum2は0より大きい値にしてください。
入力: specialSkill(1, -1)
期待値: num1とnum2は0より大きい値にしてください。(num1 > num2エラーより優先)

入力: specialSkill(0, 301)
期待値: num1とnum2は0より大きい値にしてください。(300超えエラーより優先)

※期待値どおりに出力した後動作が止まることを確認してください。

**3. num1 が num2 以上の場合**

入力: specialSkill(2, 1)
期待値: num2はnum1より大きい値にしてください。
入力: specialSkill(10, 10)
期待値: num2はnum1より大きい値にしてください。
入力: specialSkill(300, 299)
期待値: num2はnum1より大きい値にしてください。(300超えエラーより優先)

※期待値どおりに出力した後動作が止まることを確認してください。


**4. num1 または num2 が 300 より大きい場合**
入力: specialSkill(299, 301)
期待値: num1とnum2は300以下にしてください。

※期待値どおりに出力した後動作が止まることを確認してください。

2024-07-31 08:38 UTC, kuwana0425 commented
作成手順&動作確認方法まで・・・ありがとうございます😭全て確認が終わり、出力されました。こちらでいかがでしょうか？何卒よろしくお願いします🙇

2024-08-01 09:33 UTC, merged